// <auto-generated />
namespace BudzetDomowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_column_Rodzaj_to_table_RodzajeTranzakcii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_column_Rodzaj_to_table_RodzajeTranzakcii));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081918571_Add_column_Rodzaj_to_table_RodzajeTranzakcii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
